# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
version: '{build}'

# Disble stupid msbuild error thing
build_script:
  - cmd: echo 0


init:
  - git config --global core.autocrlf input

install:
  - ps: $env:COMMIT_TIMESTAMP = git log -1 --pretty=format:%ct
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64
 
  # zlib
  - cmd: git clone -b v1.2.8 https://github.com/madler/zlib.git
  - call cd zlib && nmake /f win32\Makefile.msc && cd ..

  # bzip2 
  - echo Working bzip2
  - cmd: set BZIP2_VER=1.0.6
  - cmd: echo %BZIP2_VER%
  - cmd: curl http://www.bzip.org/%BZIP2_VER%/bzip2-%BZIP2_VER%.tar.gz -o bzip2-%BZIP2_VER%.tar.gz
  - cmd: 7z x bzip2-%BZIP2_VER%.tar.gz
  - cmd: 7z x bzip2-%BZIP2_VER%.tar
  - call cd bzip2-%BZIP2_VER% && nmake /f Makefile.msc

  # boost
  - cmd: git clone -b boost-1.60.0 https://github.com/boostorg/boost.git


artifacts:
  - path: zlib
    #zlib.lib,zlib1.dll,zlib1.pdb,zdll.lib,zlib.h,zconf.h    
  - path: bzip2-%BZIP2_VER%
    #**/libbz2.lib,**/bzlib.h

on_failure:
  - dir .
