# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
version: '{build}'

# Disble stupid msbuild error thing
#build_script:
#  - cmd: echo %CD%

init:
  - git config --global core.autocrlf input
  - set WORKSPACE=%CD%

    #install:
build_script:
  - ps: $env:COMMIT_TIMESTAMP = git log -1 --pretty=format:%ct

  - call env_setup.bat
  - call build_bzip2.bat
  - call build_zlib.bat
  #- call build_boost.bat

artifacts:
  - path: zlib

    #zlib.lib,zlib1.dll,zlib1.pdb,zdll.lib,zlib.h,zconf.h    
  - path: zlib.lib,zlib1.dll,zlib1.pdb,zdll.lib,zlib.h,zconf.h
    name: files

  - path: bzip2-%BZIP2_VER%
    #**/libbz2.lib,**/bzlib.h
  - path: cache

on_failure:
  - dir .

cache:
  #  - cache

test: off  # to avoid discovering tests
