# Build worker image (VM template)
image: Visual Studio 2015

# scripts that are called at very beginning, before repo cloning
version: '{build}'

# Disble stupid msbuild error thing
build_script:
  - cmd: echo 0


init:
  - git config --global core.autocrlf input

install:
  - ps: $env:COMMIT_TIMESTAMP = git log -1 --pretty=format:%ct
  - call "C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64

  - call build_bzip2.bat
  - cmd: dir .
  - call build_zlib.bat


artifacts:
  - path: zlib

    #zlib.lib,zlib1.dll,zlib1.pdb,zdll.lib,zlib.h,zconf.h    
  - path: zlib.lib,zlib1.dll,zlib1.pdb,zdll.lib,zlib.h,zconf.h
    name: files

  - path: bzip2-%BZIP2_VER%
    #**/libbz2.lib,**/bzlib.h
  - path: cache

on_failure:
  - dir .

test: off  # to avoid discovering tests
